# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Nicolas Sommer'
tagline:          'Roboticist'
description:      'Robotics and Machine Learning'
url:              ()
baseurl:          /

author:
  name:           'Nicolas Sommer'
  # url:            https://twitter.com/mdo
linkedin:       https://www.linkedin.com/in/nicolas-sommer


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nisommer/nisommer.github.io
