# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Nicolas Sommer'
tagline:          'Roboticist'
description:      'Robotics and Machine Learning'
url:              http://www.nicolassommer.com
baseurl:          "/"

author:
  name:           'Nicolas Sommer'
  url:            http://nicolassommer.com/
  linkedin:       https://www.linkedin.com/in/nicolas-sommer
  youtube:        https://www.youtube.com/channel/UCXoCrLW5ffLEhn8AYPZMm_A
  lasa_profile:   http://lasa.epfl.ch/people/member.php?SCIPER=202511


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nisommer/nisommer.github.io
  main:           https://github.com/nisommer/
